### ISSUE TITLE
fix coveralls

### ISSUE THREAD

**Issue by jvanhoefer** [martamatos/yaml2sbml#15]
The coveralls result includes files, that only are relevant for travis runs e.g. all python site-packages... 

https://coveralls.io/builds/29862135

In other words: The coverage of `yaml2sbml` itself is >75%, but the coverage badge does not say so, since it includes files into the calculation, that are not part of the package, but rather requirements...

**Comment by jvanhoefer** [comment]
Maybe @martamatos, can you help here?

**Comment by martamatos** [comment]
Nice catch, that might explain a few things xD
I'll take a look later today :)

**Comment by martamatos** [comment]
Fixed in PR #16
