### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by jvanhoefer** [martamatos/yaml2sbml#17]
We spoke about adding more badges for the README header

**Comment by martamatos** [comment]
Did you mean codify or codacy in the bottom commit? 
(just because i can't find any service called codify, so i'm guessing you meant codacy :) )

![image](https://user-images.githubusercontent.com/609864/78800227-7f4fc180-79bb-11ea-8963-765e0c611950.png)

**Comment by jvanhoefer** [comment]
oh, yes, you are right. codify it was :)
