### ISSUE TITLE
Format documentation

### ISSUE THREAD

**Issue by jvanhoefer** [martamatos/yaml2sbml#2]
I started writing a documentation of the format including short examples...

**Comment by martamatos** [comment]
You mean high-level documentation like this: https://set-up-grasp-models.readthedocs.io/en/latest/ ?
If so, i suggest using sphinx to write it, and if you need help we can have a skype call :)

**Comment by jvanhoefer** [comment]
Am I right, that this can be generated from a mark down file? I will upload one and then contact you regarding the readthedocs part :)

**Comment by martamatos** [comment]
Not really markdown, it's .rst, which is very similar :)
You can check the source documentation files here: https://github.com/biosustain/set_up_grasp_models/tree/master/docs, from which this is built:  https://set-up-grasp-models.readthedocs.io/en/latest/  :)
