### ISSUE TITLE
PEtab as optional output.

### ISSUE THREAD

**Issue by jvanhoefer** [martamatos/yaml2sbml#3]
Recently the format for noise and observables was changed and the way we deal with it is discouraged. 

I think it would make most sense, that we add an (optional) PEtab output flag, that allows to store observables/noise in PEtab files. (Precisely: If `PEtab_output=True`, we also generate parameter+observable tables for PEtab.) In this way we allow the user to specify an SBML to simulate the ODE, and if wanted, also set up the parameter fitting procedure. 

@martamatos What do you think?

**Comment by jvanhoefer** [comment]
If you agree, I would vote to allow for optional further entries in the yams, that specify all further infos for the PEtab (e.g. upper & lower bounds for the optimization...)

**Comment by martamatos** [comment]
Let me see if i got it, the user would still specify noise and observables in the yaml file, but instead of converting that to an SBML file we'd convert it to a PEtab file. Is that it?

What should we do if the user sets `PEtab_output=False` but still specifies noise/observables in the yaml file?

**Comment by jvanhoefer** [comment]
Then I would output a warning.

**Comment by martamatos** [comment]
Sounds good to me :)
The only thing i suggest is that we implement that in a different branch and only merge with master when we are sure that it works fine :)

**Comment by jvanhoefer** [comment]
Do you mind to rename the key words according to PEtab? (e.g. `parameterId` instead of `id` for a parameter?)

**Comment by martamatos** [comment]
If you keep it consistent for all variable names, it's all good with me :)

**Comment by jvanhoefer** [comment]
In the end I decided not to do this via some `PEtab_flag`but via two different functions, since this would complicate the SBML-only-output too much otherwise.
